services:
  - type: web
    name: php-web-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    ports:
      - 80
      - 443
